/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: song16.c                                              *
* Font:        ËÎÌå                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\T\Desktop\GUIºº×Ö.txt                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_505C[ 32] = { /* code 505C */
  ___X____,X_______,
  ___X____,_X______,
  ___X_XXX,XXXXXX__,
  __X_____,________,
  __X___XX,XXXXX___,
  _XX___X_,____X___,
  _XX___XX,XXXXX___,
  X_X_____,________,
  __X_XXXX,XXXXXXX_,
  __X_X___,______X_,
  __X___XX,XXXXX___,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  __X____X,_X______,
  __X_____,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_516C[ 32] = { /* code 516C */
  ________,X_______,
  _____X__,X_______,
  _____X__,X_______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,__X_____,
  __X_____,___X____,
  _X____X_,____X___,
  X_____X_,_____XX_,
  _____X__,________,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,__X_____,
  __XXXXXX,XXXX____,
  ___X____,___X____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_517B[ 32] = { /* code 517B */
  ____X___,__X_____,
  _____X__,_X______,
  ________,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  __XXXXXX,XXXXX___,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  _____X__,_X______,
  ____X___,__X_____,
  __XX_X__,_X_XX___,
  XX___X__,_X___XX_,
  _____X__,_X______,
  ____X___,_X______,
  ___X____,_X______,
  __X_____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_533B[ 32] = { /* code 533B */
  ________,________,
  _XXXXXXX,XXXXXX__,
  _X___X__,________,
  _X___X__,________,
  _X__XXXX,XXXXX___,
  _X_X____,X_______,
  _X______,X_______,
  _X_XXXXX,XXXXXX__,
  _X______,X_______,
  _X_____X,_X______,
  _X____X_,__X_____,
  _X___X__,___X____,
  _X_XX___,____X___,
  _X______,________,
  _XXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_53F8[ 32] = { /* code 53F8 */
  ________,________,
  __XXXXXX,XXXXX___,
  ________,____X___,
  ________,____X___,
  _XXXXXXX,XXX_X___,
  ________,____X___,
  ________,____X___,
  ___XXXXX,X___X___,
  ___X____,X___X___,
  ___X____,X___X___,
  ___X____,X___X___,
  ___X____,X___X___,
  ___XXXXX,X___X___,
  ___X____,X___X___,
  ________,__X_X___,
  ________,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_548C[ 32] = { /* code 548C */
  _____X__,________,
  ____XXX_,________,
  _XXXX___,________,
  ____X___,_XXXXX__,
  ____X___,_X___X__,
  XXXXXXXX,_X___X__,
  ____X___,_X___X__,
  ___XX___,_X___X__,
  ___XXX__,_X___X__,
  __X_X_X_,_X___X__,
  __X_X_X_,_X___X__,
  _X__X___,_X___X__,
  X___X___,_XXXXX__,
  ____X___,_X___X__,
  ____X___,________,
  ____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_54C1[ 32] = { /* code 54C1 */
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ________,________,
  ________,________,
  _XXXXX__,_XXXXX__,
  _X___X__,_X___X__,
  _X___X__,_X___X__,
  _X___X__,_X___X__,
  _X___X__,_X___X__,
  _XXXXX__,_XXXXX__,
  _X___X__,_X___X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5668[ 32] = { /* code 5668 */
  ________,________,
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__,
  _______X,__X_____,
  _______X,___X____,
  XXXXXXXX,XXXXXXX_,
  ______X_,X_______,
  ____XX__,_XX_____,
  __XX____,___XX___,
  XX______,_____XX_,
  __XXXXX_,_XXXXX__,
  __X___X_,_X___X__,
  __X___X_,_X___X__,
  __XXXXX_,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5907[ 32] = { /* code 5907 */
  _____X__,________,
  _____X__,________,
  ____XXXX,XXXX____,
  ___XX___,__X_____,
  _XX__X__,_X______,
  ______XX,X_______,
  ___XXX__,_XXX____,
  XXX_____,____XXX_,
  ___XXXXX,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___XXXXX,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5B89[ 32] = { /* code 5B89 */
  ______X_,________,
  _______X,________,
  __XXXXXX,XXXXXX__,
  __X_____,_____X__,
  _X____X_,____X___,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  _____X__,__X_____,
  ____X___,__X_____,
  ___XX___,_X______,
  _____XX_,_X______,
  _______X,X_______,
  ______X_,_XX_____,
  ____XX__,___X____,
  _XXX____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5FBD[ 32] = { /* code 5FBD */
  ___X__X_,___X____,
  ___XX_X_,X__X____,
  __X_X_X_,X__X____,
  _X__XXXX,X_X_____,
  X_______,__XXXXX_,
  ___XXXXX,XX___X__,
  __X__X__,__X__X__,
  _XX_X___,X_X__X__,
  X_X_XXXX,__X__X__,
  __X___X_,__X_X___,
  __X__X__,X_X_X___,
  __XXXXXX,XX_X____,
  __X___X_,__X_X___,
  __X_X_X_,X_X_X___,
  __XX__X_,_X___X__,
  __X__XX_,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6709[ 32] = { /* code 6709 */
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  _____X__,________,
  _____X__,________,
  ____XXXX,XXXX____,
  ____X___,___X____,
  ___XX___,___X____,
  __X_XXXX,XXXX____,
  _X__X___,___X____,
  X___X___,___X____,
  ____XXXX,XXXX____,
  ____X___,___X____,
  ____X___,___X____,
  ____X___,_X_X____,
  ____X___,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6837[ 32] = { /* code 6837 */
  ___X___X,_____X__,
  ___X____,X____X__,
  ___X____,X___X___,
  ___X____,________,
  XXXXX_XX,XXXXXXX_,
  ___X____,__X_____,
  __XX____,__X_____,
  __XXX__X,XXXXXX__,
  _X_X_X__,__X_____,
  _X_X____,__X_____,
  X__X__XX,XXXXXXX_,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_68B0[ 32] = { /* code 68B0 */
  ___X____,___X____,
  ___X____,___X_X__,
  ___X____,___X__X_,
  ___X____,___X____,
  XXXXX_XX,XXXXXXX_,
  ___X____,___X____,
  __XX___X,_X_X____,
  __XXX__X,_X_X_X__,
  _X_X_XXX,XXXX_X__,
  _X_X___X,_X_X_X__,
  X__X___X,_X_X_X__,
  ___X___X,_X__X___,
  ___X__X_,_X__X_X_,
  ___X__X_,_X_XX_X_,
  ___X_X__,__X__XX_,
  ___X____,_X____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_68C0[ 32] = { /* code 68C0 */
  ___X____,_X______,
  ___X____,_X______,
  ___X____,X_X_____,
  ___X____,X_X_____,
  XXXXXX_X,___X____,
  ___X__X_,____X___,
  __XX_X_X,XXXX_XX_,
  __XXX___,________,
  _X_X_X__,X___X___,
  _X_X____,_X__X___,
  X__X__X_,_X__X___,
  ___X___X,_X_X____,
  ___X___X,___X____,
  ___X____,__X_____,
  ___X_XXX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6B62[ 32] = { /* code 6B62 */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,XXXXX___,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6D4B[ 32] = { /* code 6D4B */
  ________,_____X__,
  __X__XXX,XX___X__,
  ___X_X__,_X___X__,
  ___X_X__,_X_X_X__,
  X____X_X,_X_X_X__,
  _X___X_X,_X_X_X__,
  _X___X_X,_X_X_X__,
  ___X_X_X,_X_X_X__,
  ___X_X_X,_X_X_X__,
  __X__X_X,_X_X_X__,
  XXX__X_X,_X_X_X__,
  __X____X,_____X__,
  __X___X_,X____X__,
  __X___X_,_X___X__,
  __X__X__,___X_X__,
  ____X___,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_7597[ 32] = { /* code 7597 */
  ________,X_______,
  ________,_X______,
  ___XXXXX,XXXXXXX_,
  ___X____,________,
  X__X____,________,
  _X_X_XXX,XXXXXX__,
  _X_X____,____X___,
  ___X____,___X____,
  __XX____,__X_____,
  _X_X____,_X______,
  X__X____,_X______,
  ___X____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  _X_____X,_X______,
  X_______,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_8BBE[ 32] = { /* code 8BBE */
  ________,________,
  __X____X,XXXX____,
  ___X___X,___X____,
  ___X___X,___X____,
  _______X,___X____,
  ______X_,____XXX_,
  XXXX_X__,________,
  ___X__XX,XXXXX___,
  ___X___X,____X___,
  ___X___X,___X____,
  ___X____,X__X____,
  ___X_X__,X_X_____,
  ___XX___,_X______,
  ___X____,X_X_____,
  ______XX,___XX___,
  ____XX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_91CF[ 32] = { /* code 91CF */
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ___XXXXX,XXXX____,
  ___X___X,___X____,
  ___XXXXX,XXXX____,
  ___X___X,___X____,
  ___XXXXX,XXXX____,
  _______X,________,
  ___XXXXX,XXXX____,
  _______X,________,
  _XXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_9650[ 32] = { /* code 9650 */
  ________,________,
  _XXXX_XX,XXXXX___,
  _X__X_X_,____X___,
  _X_X__X_,____X___,
  _X_X__XX,XXXXX___,
  _XX___X_,____X___,
  _X_X__X_,____X___,
  _X__X_XX,XXXXX___,
  _X__X_X_,_X___X__,
  _X__X_X_,_X__X___,
  _XX_X_X_,__XX____,
  _X_X__X_,__X_____,
  _X____X_,___X____,
  _X____X_,X___X___,
  _X____XX,_____XX_,
  _X____X_,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsong16_CharInfo[21] = {
   {  16,  16,  2, acGUI_Fontsong16_505C } /* code 505C */
  ,{  16,  16,  2, acGUI_Fontsong16_516C } /* code 516C */
  ,{  16,  16,  2, acGUI_Fontsong16_517B } /* code 517B */
  ,{  16,  16,  2, acGUI_Fontsong16_533B } /* code 533B */
  ,{  16,  16,  2, acGUI_Fontsong16_53F8 } /* code 53F8 */
  ,{  16,  16,  2, acGUI_Fontsong16_548C } /* code 548C */
  ,{  16,  16,  2, acGUI_Fontsong16_54C1 } /* code 54C1 */
  ,{  16,  16,  2, acGUI_Fontsong16_5668 } /* code 5668 */
  ,{  16,  16,  2, acGUI_Fontsong16_5907 } /* code 5907 */
  ,{  16,  16,  2, acGUI_Fontsong16_5B89 } /* code 5B89 */
  ,{  16,  16,  2, acGUI_Fontsong16_5FBD } /* code 5FBD */
  ,{  16,  16,  2, acGUI_Fontsong16_6709 } /* code 6709 */
  ,{  16,  16,  2, acGUI_Fontsong16_6837 } /* code 6837 */
  ,{  16,  16,  2, acGUI_Fontsong16_68B0 } /* code 68B0 */
  ,{  16,  16,  2, acGUI_Fontsong16_68C0 } /* code 68C0 */
  ,{  16,  16,  2, acGUI_Fontsong16_6B62 } /* code 6B62 */
  ,{  16,  16,  2, acGUI_Fontsong16_6D4B } /* code 6D4B */
  ,{  16,  16,  2, acGUI_Fontsong16_7597 } /* code 7597 */
  ,{  16,  16,  2, acGUI_Fontsong16_8BBE } /* code 8BBE */
  ,{  16,  16,  2, acGUI_Fontsong16_91CF } /* code 91CF */
  ,{  16,  16,  2, acGUI_Fontsong16_9650 } /* code 9650 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop21 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 20] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop20 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 19] /* address of first character */
  ,&GUI_Fontsong16_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop19 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontsong16_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop18 = {
   0x7597 /* first character */
  ,0x7597 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontsong16_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop17 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontsong16_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop16 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontsong16_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop15 = {
   0x68C0 /* first character */
  ,0x68C0 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontsong16_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop14 = {
   0x68B0 /* first character */
  ,0x68B0 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontsong16_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop13 = {
   0x6837 /* first character */
  ,0x6837 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontsong16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop12 = {
   0x6709 /* first character */
  ,0x6709 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontsong16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop11 = {
   0x5FBD /* first character */
  ,0x5FBD /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontsong16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop10 = {
   0x5B89 /* first character */
  ,0x5B89 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  9] /* address of first character */
  ,&GUI_Fontsong16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop9 = {
   0x5907 /* first character */
  ,0x5907 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  8] /* address of first character */
  ,&GUI_Fontsong16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop8 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  7] /* address of first character */
  ,&GUI_Fontsong16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop7 = {
   0x54C1 /* first character */
  ,0x54C1 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  6] /* address of first character */
  ,&GUI_Fontsong16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop6 = {
   0x548C /* first character */
  ,0x548C /* last character  */
  ,&GUI_Fontsong16_CharInfo[  5] /* address of first character */
  ,&GUI_Fontsong16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop5 = {
   0x53F8 /* first character */
  ,0x53F8 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  4] /* address of first character */
  ,&GUI_Fontsong16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop4 = {
   0x533B /* first character */
  ,0x533B /* last character  */
  ,&GUI_Fontsong16_CharInfo[  3] /* address of first character */
  ,&GUI_Fontsong16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop3 = {
   0x517B /* first character */
  ,0x517B /* last character  */
  ,&GUI_Fontsong16_CharInfo[  2] /* address of first character */
  ,&GUI_Fontsong16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop2 = {
   0x516C /* first character */
  ,0x516C /* last character  */
  ,&GUI_Fontsong16_CharInfo[  1] /* address of first character */
  ,&GUI_Fontsong16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop1 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_Fontsong16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsong16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsong16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsong16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

